name: Deploy Node App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/my-node-app || git clone https://github.com/saurabh12571257/sample_proj.git
            cd ~/my-node-app
            git pull origin main
            npm install
            # Stop any existing app (if running)
            pkill -f "node app.js" || true
            # Run the app in background
            nohup node app.js > app.log 2>&1 &
          EOF
